#ifndef CONFIG_H
#define CONFIG_H

/**
 * @file Config.h
 * @brief REDIRECTS TO MASTER CONFIG
 *
 * This file is kept for backward compatibility.
 * All settings are now in SystemConfig.h
 *
 * ⚠️ DO NOT EDIT THIS FILE
 * ✅ Edit SystemConfig.h instead
 */

#include "SystemConfig.h"

#endif